Layout/ExtraSpacing:
  Exclude:
    - Gemfile

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - spec/*/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/*/**/*.rb

Metrics/LineLength:
  Max: 100
  Exclude:
    - spec/*/**/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  MinNameLength: 2
