sudo: false

language: ruby
rvm:
  - 2.5.3
  - 2.6.0

branches:
  only:
    - master
    - develop

install:
  - gem install bundler
  - bundle install --deployment
cache: bundler

script:
  - bundle exec rspec --exclude-pattern spec/browser/**/*.rb
  - bundle exec jekyll b
  - bundle exec rspec --pattern spec/browser/**/*.rb
  - bundle exec htmlproofer _site/ --disable-external --check-html --log-level :warn

before_deploy:
  - openssl aes-256-cbc -K "$encrypted_e735c587144c_key" -iv "$encrypted_e735c587144c_iv" -in .travis/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
    find "$TRAVIS_BUILD_DIR/_site" -type f -exec chmod 604 {} \; &&
    find "$TRAVIS_BUILD_DIR/_site" -type d -exec chmod 701 {} \; &&
    rsync -qrpt --delete-after "$TRAVIS_BUILD_DIR/_site/" http@sueka.me:/opt/local/http/me/sueka/www/html
  on:
    rvm: 2.5.3
    branch: master

addons:
  apt:
    packages:
      - libgsl0-dev
  ssh_known_hosts:
    - sueka.me
    - 133.130.114.209

notifications:
  email:
    on_success: never
    on_failure: change
