sudo: false
language: ruby
rvm:
  - 2.3.5
  - 2.4.3
  - 2.5.0
install:
  - gem install bundler
  - bundle install --deployment
cache: bundler
script:
  - bundle exec jekyll b --safe -s source
  - bundle exec htmlproofer _site/ --disable-external
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e735c587144c_key -iv $encrypted_e735c587144c_iv
    -in .travis/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
    find $TRAVIS_BUILD_DIR/_site -type f -print | xargs chmod 604 &&
    find $TRAVIS_BUILD_DIR/_site -type d -print | xargs chmod 701 &&
    rsync -qrpt --delete-after $TRAVIS_BUILD_DIR/_site/ http@sueka.me:/srv/http/www/html
  on:
    rvm: 2.4.3
    branch:
      - master
addons:
  ssh_known_hosts:
    - sueka.me
branches:
  only:
    - master
    - develop
notifications:
  email:
    on_success: never
    on_failure: change
