sudo: false
language: ruby
rvm: 2.4.1
install:
  - gem install bundler
  - bundle install --deployment
  - git clone --depth=1 --branch=master https://github.com/sueka/posts.sueka.me.git ~/sueka/posts.sueka.me
  - cp -r ~/sueka/posts.sueka.me/_posts ~/sueka/sueka.me/
cashe:
  directories: vendor/bundle
script:
  - bundle exec jekyll b --safe
  - bundle exec htmlproofer _site/ --disable-external
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e735c587144c_key -iv $encrypted_e735c587144c_iv -in .travis/id_rsa.enc -out /tmp/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/deploy.sh
  on:
    branch:
      - master
      - develop
addons:
  ssh_known_hosts: sueka.me
branches:
  only:
    - master
    - develop
notifications:
  email:
    on_success: never
    on_failure: change
