title: sueka.me
lang: en
url: http://sueka.me
github_repo: sueka/sueka.me
license: CC0
license_url: https://creativecommons.org/publicdomain/zero/1.0/

author: sueka
email: mail-nospam@sueka.me
pgp_key_id: D178285D
pks_url: https://sks-keyservers.net/pks/lookup?op=get&search=0x5B60E6C7D178285D
twitter_username: hsueka
github_username: sueka

exclude:
  - spec/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
  - UNLICENSE.txt

collections:
  posts:
    permalink: /:categories/:year/:month/:slug.html
  apps:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: apps
    values:
      layout: app

markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-coffeescript
