title: sueka.me
lang: ja
url: https://sueka.me
github_repo: sueka/sueka.me
license: CC0
license_url: https://creativecommons.org/publicdomain/zero/1.0/
katex_version: 0.9.0
incremental_dom_version: 0.5.1

author:
  name: Sueka
  email: suekaq@gmail.com
  twitter: hsueka
  github: sueka

defaults:
  - values:
      lang: ja
      h1: true
source: source/
lsi: true

collections:
  posts:
    permalink: /:year/:month/:title.html

liquid:
  error_mode: strict

markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-archives
  - jekyll-coffeescript
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jemoji

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  permalink: /pages/:num/
  title: ':title'

jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: year-archives
    month: month-archives
  permalinks:
    year: /:year/
    month: /:year/:month/

katex:
  rendering_options:
    strict: true
