title: sueka.me
lang: en
url: https://sueka.me
github_repo: sueka/sueka.me
license: CC0
license_url: https://creativecommons.org/publicdomain/zero/1.0/
katex_version: 0.6.0
fetch_version: 2.0.3
es6_promise_version: 4.1.1
incremental_dom_version: 0.5.1

author: Sueka
email: suekaq@gmail.com
pgp_key_id: D178285D
pks_url: https://sks-keyservers.net/pks/lookup?op=get&search=0x5B60E6C7D178285D
twitter_username: hsueka
github_username: sueka

source: source/
lsi: true

collections:
  posts:
    permalink: /:year/:month/:title.html

liquid:
  error_mode: strict

assets:
  sources:
    - _sass
    - assets
  plugins:
    css:
      autoprefixer: null
  autoprefixer:
    browsers:
      - 'last 2 versions'
      - '> 2%'
      - 'IE >= 10'

markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-archives
  - jekyll-coffeescript
  - jemoji

jekyll-archives:
  layout: archives
  enabled:
    - year
    - month
    - tags
  permalinks:
    year: /:year/
    month: /:year/:month/
    tag: /tags/:name.html
