on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ~1.25
      - uses: actions/cache@v3
        with:
          # See also https://deno.land/manual@v1.24.3/linking_to_external_code
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ hashFiles('lock.json') }}
      - name: Build
        env:
          TZ: Asia/Tokyo
        run: |
          timeout 60s deno run --allow-all --quiet https://deno.land/x/lume/ci.ts
          exit_status=$?
          (( $exit_status == 0 )) || (( $exit_status == 124 ))
        shell: bash -o pipefail {0}
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        # github.ref must be in the form refs/pull/:prNumber/merge when the workflow event is a pull_request. See also https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request.
        if: github.ref == 'refs/heads/master'
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.install.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        uses: actions/configure-pages@v2
      - name: Install
        id: install
        uses: actions/deploy-pages@v1
    needs:
      - build
    if: github.ref == 'refs/heads/master'
