on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Default value on Linux, which running `deno info` displays. See also https://deno.land/manual@v1.32.1/tools/dependency_inspector#cache-location.
      DENO_DIR: ~/.cache/deno
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ~1.32.1
      - uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          # Run `deno task serve` to keep deno.lock up-to-date
          key: ${{ hashFiles('deno.lock') }}
      - name: Build
        env:
          TZ: Asia/Tokyo
        run: deno task build
        shell: bash -o pipefail {0}
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v1
        if: github.event_name == 'push'
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.install.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        uses: actions/configure-pages@v2
      - name: Install
        id: install
        uses: actions/deploy-pages@v1
    needs:
      - build
    if: github.ref == 'refs/heads/master'
