on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ~1.21
      - name: Build
        env:
          TZ: Asia/Tokyo
        run: deno run --allow-all --quiet https://deno.land/x/lume/ci.ts
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site
        # github.ref must be in the form refs/pull/:prNumber/merge when the workflow event is a pull_request. See also https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request.
        if: github.ref == 'refs/heads/master'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: sueka.me
    needs:
      - build
    if: github.ref == 'refs/heads/master'
